permalink: /:year:month:day/:title
url: reddresseson.github.io
baseurl: /intro

# variables
name: This is reddresseson's blog
description: I want to be good with git...
google_verification: null


# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE"]

# Sass
sass:
  style: :compressed
  sass_dir: _sass

# Markdown
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    disable : true